# -*- coding: utf-8 -*-
"""ilkadim.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ceWIMmWy6uqGjCsZ21n53nws3LH9LTz7

## İLK ADIM'da COLAB servisini nasıl kullanabilirim sorusunun cevaplarını bulabilirsiniz. 


---


**Kaynak: **[Google Colab ile Ücretsiz GPU Kullanımı Videolu Anlatım ](https://www.youtube.com/watch?v=bT-T1i_Rpy8&t=3s) 

[<img align="right" width="100" height="100" src="http://www.i2symbol.com/images/symbols/style-letters/circled_latin_capital_letter_a_u24B6_icon_128x128.png">](https://www.ayyucekizrak.com/)

**Colab** için kimlik doğrulama admlarını gerçekleştirme...
"""

from google.colab import drive
drive.mount('/content/drive/')

import sys
sys.path.insert(0, 'drive/My Drive/Udemy_DerinOgrenmeyeGiris/Evrisimli_Sinir_Aglari/')

!mkdir -p drive

!ls "drive/My Drive/Udemy_DerinOgrenmeyeGiris/Evrisimli_Sinir_Aglari/"

"""### Kütüphane Kulumu"""

!pip install -q keras

"""### `.py` uzantılı bir dosyayı Colab üzerinden çağırarak çalıştırma!!!"""

!python3 drive/My Drive/Udemy_DerinOgrenmeyeGiris/Evrisimli_Sinir_Aglari/rakamtanima_cnn.py